import os
from datetime import datetime
from fpdf import FPDF
from dataclasses import dataclass, field
from typing import List, Dict, Any

@dataclass
class ReportConfig:
    filename: str
    title: str
    program_description: str
    # Now a template string where you can embed any keys from `data`
    parameters_description: str
    data: Dict[str, Any]
    image_files: List[str] = field(default_factory=list)
    image_captions: List[str] = field(default_factory=list)
    output_dir: str = 'assets_convAera'

class PDFReport(FPDF):
    """
    Custom PDF class that adds a header and footer to each page, skipping the cover page.
    """
    def __init__(self, title: str):
        super().__init__()
        self.title = title

    def header(self) -> None:
        if self.page_no() == 1:
            return
        self.set_font('Arial', 'B', 15)
        title_w = self.get_string_width(self.title) + 6
        self.set_x((self.w - title_w) / 2)
        self.cell(title_w, 10, self.title, border=False, ln=True, align='C')
        self.ln(5)

    def footer(self) -> None:
        if self.page_no() == 1:
            return
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        page_text = f'Page {self.page_no()}/{{nb}}'
        self.cell(0, 10, page_text, align='C')


def create_pdf_report(config: ReportConfig) -> None:
    """
    Generates a PDF report based on a ReportConfig object.

    The `parameters_description` field is treated as a Python format string and
    formatted with the contents of `config.data`.
    """
    # Prepare output path
    if config.output_dir:
        os.makedirs(config.output_dir, exist_ok=True)
        output_path = os.path.join(config.output_dir, config.filename)
    else:
        output_path = config.filename

    pdf = PDFReport(config.title)
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- Cover Page ---
    pdf.add_page()
    pdf.set_font('Arial', 'B', 24)
    pdf.ln(40)
    pdf.cell(0, 10, config.title, ln=True, align='C')
    pdf.ln(10)
    pdf.set_font('Arial', '', 14)
    date_str = datetime.now().strftime('%B %d, %Y')
    pdf.cell(0, 10, f'Date: {date_str}', ln=True, align='C')
    pdf.ln(20)
    pdf.set_font('Arial', 'I', 12)
    pdf.multi_cell(0, 8, config.program_description, align='J')

    # --- Introduction / Parameters Description ---
    pdf.add_page()
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'Introduction', ln=True)
    pdf.ln(5)
    pdf.set_font('Arial', '', 12)
    pdf.multi_cell(0, 8, config.program_description, align='J')
    pdf.ln(10)
    pdf.set_font('Arial', 'B', 16)
    pdf.cell(0, 10, 'Chosen Parameters', ln=True)
    pdf.ln(5)
    pdf.set_font('Arial', '', 12)
    # Format the template with data values
    formatted_params = config.parameters_description.format(**config.data)
    pdf.multi_cell(0, 8, formatted_params, align='J')

    # --- Images with Captions ---
    for idx, img_path in enumerate(config.image_files):
        pdf.add_page()
        try:
            usable_width = pdf.w - pdf.l_margin - pdf.r_margin
            pdf.image(img_path, w=usable_width)
            pdf.ln(5)
        except RuntimeError:
            pdf.set_font('Arial', 'I', 10)
            pdf.cell(0, 8, f"[Could not load image: {img_path}]")
            pdf.ln(5)
        caption = config.image_captions[idx] if idx < len(config.image_captions) else ''
        pdf.set_font('Arial', 'I', 11)
        pdf.multi_cell(0, 6, caption, align='C')

    # --- Results Table ---
    pdf.add_page()
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Results', ln=True)
    pdf.ln(5)
    usable_width = pdf.w - pdf.l_margin - pdf.r_margin
    col_width = usable_width / 2
    row_height = pdf.font_size * 2
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(200, 200, 200)
    pdf.cell(col_width, row_height, 'Parameter', border=1, fill=True)
    pdf.cell(col_width, row_height, 'Value', border=1, fill=True, ln=True)
    pdf.set_font('Arial', '', 12)
    for key, value in config.data.items():
        pdf.cell(col_width, row_height, str(key), border=1)
        pdf.cell(col_width, row_height, str(value), border=1, ln=True)

    # Output PDF
    pdf.output(output_path)

# Example usage
if __name__ == '__main__':
    config = ReportConfig(
        filename='convAera_report.pdf',
        title='ConvAera AVL Analysis Results',
        program_description=(
            'This report was generated by ConvAera, which interfaces with AVL to perform aerodynamic analysis'
            ' on aircraft geometries. It computes lift-to-drag ratios, total lift, and other performance metrics.'
        ),
        # Use placeholders matching keys from `data`
        parameters_description=(
            'The analysis was run at a fixed angle of attack (AoA) of {AoA} degrees and then trimmed for '
            'zero pitching moment. Computed values: L/D_fixed={L/D (fixed AoA)} and total lift={Total Lift (fixed AoA)}.'
        ),
        data={
            'AoA': 5,
            'L/D (fixed AoA)': 8.2,
            'Total Lift (fixed AoA)': 0.45,
            'L/D (trimmed)': 7.8,
            'Total Lift (trimmed)': 0.42,
        },
        image_files=['assets_convAera/M_1-geometry.jpeg', 'assets_convAera/M_1-trefftz-0.jpeg'],
        image_captions=['Geometry of the model.', 'Trefftz plane distribution.'],
        output_dir='assets_convAera'
    )
    create_pdf_report(config)
    print('PDF report generated at:', os.path.join(config.output_dir or '.', config.filename))
