from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from parapy.webgui import html, mui, viewer
from parapy.webgui.core import Component, get_asset_url, get_assets_dir
from parapy.webgui.core.actions import download_file
from parapy.webgui.layout import Box, MarginTop
from parapy.webgui.layout.core.sizing import VerticalScroll
from persistence import PERSISTENCE_DISABLED
from persistence.client import client
from ui.components.cost_graph import CostGraph
from ui.components.property_table import PropertyTable
from ui.store import STORE

if TYPE_CHECKING:
    from parapy.webgui.core.node import NodeType


class ReportingStep(Component):
    def save_report(self, *args: Any) -> None:
        if PERSISTENCE_DISABLED:
            return

        report_location = Path(get_assets_dir()) / "Report.pdf"
        with client.session() as session:
            session.files.stage(
                local_path=report_location,
                remote_path=report_location.name,
            )
            session.commit()

    def content(self) -> NodeType:
        model = STORE.final_design
        revenue = model.cost_revenue
        roi = (revenue[-1][1] - revenue[-1][0]) / revenue[-1][0]
        return [
            mui.Typography(variant="h3")["Report"],
            Box(h_align="center")[
                html.img(src=get_asset_url("logo.png"), style={"height": "10em"})
            ],
            mui.Typography[
                "A hot air balloon is a lighter-than-air aircraft consisting of a bag, called an envelope, which contains heated air. Suspended beneath is a gondola or wicker basket (in some long-distance or high-altitude balloons, a capsule), which carries passengers and a source of heat, in most cases an open flame caused by burning liquid propane. The heated air inside the envelope makes it buoyant, since it has a lower density than the colder air outside the envelope. As with all aircraft, hot air balloons cannot fly beyond the atmosphere. The envelope does not have to be sealed at the bottom, since the air inside the envelope is at about the same pressure as the surrounding air. In modern sport balloons the envelope is generally made from nylon fabric, and the inlet of the balloon (closest to the burner flame) is made from a fire-resistant material such as Nomex. Modern balloons have been made in many shapes, such as rocket ships and the shapes of various commercial products, though the traditional shape is used for most non-commercial and many commercial applications."
            ],
            mui.Divider(className="divider"),
            mui.Typography(variant="h5")["Chosen model:"],
            Box(h_align="center", height="400px")[
                viewer.Viewer(
                    objects=model,
                    buttonBar=False,
                    tessellation_config={"mesh_deflection": 0.01},
                )
            ],
            mui.Divider(className="divider"),
            mui.Typography(variant="h5")["Model properties"],
            mui.Typography[
                f"With a impressive volume of {round(model.volume)} cubic meter the chosen hot air balloon has a incredible lifting capibility. In fact it can carry a max payload of {round(model.weight)} kg. This is a significant payload which can be used to carry passengers. This will create revenue through flights."
            ],
            Box(h_align="center")[PropertyTable(model=STORE.final_design)],
            mui.Divider(className="divider"),
            mui.Typography(variant="h5")["Cost model"],
            mui.Typography[
                'In accounting, revenue is the total amount of income generated by the sale of goods and services related to the primary operations of the business. Commercial revenue may also be referred to as sales or as turnover. Some companies receive revenue from interest, royalties, or other fees. "Revenue" may refer to income in general, or it may refer to the amount, in a monetary unit, earned during a period of time, as in "Last year, Company X had revenue of $42 million". Profits or net income generally imply total revenue minus total expenses in a given period. In accounting, in the balance statement, revenue is a subsection of the Equity section and revenue increases equity, it is often referred to as the "top line" due to its position on the income statement at the very top. This is to be contrasted with the "bottom line" which denotes net income (gross revenues minus total expenses).'
            ],
            html.br(),
            mui.Typography["The expected return on investment in 8 years is:"],
            Box(h_align="center")[
                mui.Typography(
                    variant="h1",
                    style={
                        "color": "rgb(100, 250, 100)"
                        if roi > 0
                        else "rgb(250, 100, 100)"
                    },
                )[f"{roi:.0%}"],
            ],
            mui.Typography["Here is a table that show this result:"],
            Box(h_align="center")[CostGraph(model=STORE.final_design)],
            mui.Divider(className="divider"),
        ]

    def render(self) -> NodeType:
        # we add a vertical scroll, so that everything that this box will get
        # a scrollbar if its children get too big
        return VerticalScroll[
            Box(
                style={
                    "backgroundColor": "rgba(15,15,0,0.2)",
                    "position": "relative",
                }
            )[
                mui.Container(style={"backgroundColor": "white"})[
                    MarginTop("2em")[
                        Box(orientation="vertical", gap="2em")[self.content()]
                    ]
                ]
            ],
            mui.Tooltip(title="Save the report to Datastore")[
                mui.Fab(
                    style={
                        "position": "absolute",
                        "right": "3em",
                        "bottom": "9em",
                    },
                    color="secondary",
                    size="large",
                    onClick=self.save_report,
                    disabled=PERSISTENCE_DISABLED,
                )[mui.Icon["save"]]
            ],
            mui.Tooltip(title="Download the report")[
                mui.Fab(
                    style={
                        "position": "absolute",
                        "right": "3em",
                        "bottom": "3em",
                    },
                    color="primary",
                    size="large",
                    onClick=lambda evt: download_file(get_asset_url("Report.pdf")),
                )[mui.Icon["download"]]
            ],
        ]


if __name__ == "__main__":
    from model.balloon import HotAirBalloon
    from parapy.webgui.core import display

    STORE.final_design = HotAirBalloon()
    display(ReportingStep, reload=True)
